on: [push]
name: Docker workflow
jobs:
  docker:
    runs-on: ubuntu-20.04
    # if: github.event_name == 'push' && (startsWith(github.event.ref, 'refs/tags/') || startsWith(github.event.ref, 'refs/heads/v0.'))
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3.5.0
        with:
          images: r.haishan.me/pgbouncer

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }}
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          registry: r.haishan.me
          username: ${{ secrets.DOCKER_REG_NAME }}
          password: ${{ secrets.DOCKER_REG_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            VERSION=1.16.0

      - name: Send Notification
        uses: haishanh/actions-telegram-notification@v1
        if: ${{ always() }}
        with:
          notification-token: ${{ secrets.TG_NOTIFICATION_TOKEN }}
          job-status: ${{ job.status }}
